# Generated by Django 6.0.5 on 2026-05-08 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grid_x', models.IntegerField()),
                ('grid_z', models.IntegerField()),
                ('grid_y', models.IntegerField(default=0)),
                ('world_x', models.FloatField(default=0.0)),
                ('world_y', models.FloatField(default=0.0)),
                ('world_z', models.FloatField(default=0.0)),
                ('chunk_type', models.CharField(choices=[('void', 'Пустота'), ('empty', 'Пустой (только ландшафт)'), ('full', 'Полный (с объектами)')], default='void', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_loaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Чанк',
                'verbose_name_plural': 'Чанки',
            },
        ),
        migrations.CreateModel(
            name='ChunkVertex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('world_x', models.FloatField()),
                ('world_y', models.FloatField()),
                ('world_z', models.FloatField()),
                ('height', models.FloatField(default=0.0)),
                ('material_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Вершина стыковки',
                'verbose_name_plural': 'Вершины стыковки',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('grid_type', models.CharField(choices=[('hex', 'Гексагональная'), ('square', 'Квадратная (запасной вариант)')], default='hex', max_length=10)),
                ('chunk_size', models.FloatField(default=500.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Мир',
                'verbose_name_plural': 'Миры',
            },
        ),
        migrations.CreateModel(
            name='WorldObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('object_type', models.CharField(choices=[('mesh', 'Меш'), ('light', 'Источник света'), ('spawn', 'Точка спавна'), ('trigger', 'Триггер-зона'), ('empty', 'Пустой (только трансформация)')], default='mesh', max_length=30)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('scale_x', models.FloatField(default=1.0)),
                ('scale_y', models.FloatField(default=1.0)),
                ('scale_z', models.FloatField(default=1.0)),
                ('mesh_asset_id', models.UUIDField(blank=True, null=True)),
                ('material_asset_id', models.UUIDField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объект мира',
                'verbose_name_plural': 'Объекты мира',
            },
        ),
    ]
