# Generated by Django 6.0.5 on 2026-05-09 05:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grid_q', models.IntegerField(default=0)),
                ('grid_r', models.IntegerField(default=0)),
                ('grid_s', models.IntegerField(default=0)),
                ('grid_y', models.IntegerField(default=0)),
                ('world_x', models.FloatField(default=0.0)),
                ('world_y', models.FloatField(default=0.0)),
                ('world_z', models.FloatField(default=0.0)),
                ('chunk_type', models.CharField(choices=[('void', 'Пустота — не существует'), ('empty', 'Пустой — только ландшафт, без объектов'), ('full', 'Полный — с объектами')], default='void', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('top_vertex_x', models.FloatField(default=0.0)),
                ('top_vertex_y', models.FloatField(default=250.0)),
                ('top_vertex_z', models.FloatField(default=0.0)),
                ('bottom_vertex_x', models.FloatField(default=0.0)),
                ('bottom_vertex_y', models.FloatField(default=-250.0)),
                ('bottom_vertex_z', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_loaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Чанк (шестигранная сота)',
                'verbose_name_plural': 'Чанки (шестигранные соты)',
            },
        ),
        migrations.CreateModel(
            name='ChunkVertex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('world_x', models.FloatField()),
                ('world_y', models.FloatField()),
                ('world_z', models.FloatField()),
                ('height', models.FloatField(default=0.0)),
                ('material_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Вершина стыковки',
                'verbose_name_plural': 'Вершины стыковки',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Новый мир', max_length=200)),
                ('grid_type', models.CharField(choices=[('hex', 'Гексагональная (COR Sota)')], default='hex', max_length=10)),
                ('chunk_size', models.FloatField(default=500.0)),
                ('max_chunks_horizontal', models.IntegerField(default=100)),
                ('max_chunks_vertical', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Мир',
                'verbose_name_plural': 'Миры',
            },
        ),
        migrations.CreateModel(
            name='WorldLighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambient_color', models.CharField(default='#404060', max_length=7)),
                ('ambient_intensity', models.FloatField(default=0.5)),
                ('sun_enabled', models.BooleanField(default=True)),
                ('sun_color', models.CharField(default='#ffffff', max_length=7)),
                ('sun_intensity', models.FloatField(default=1.0)),
                ('sun_rotation_x', models.FloatField(default=45.0)),
                ('sun_rotation_y', models.FloatField(default=30.0)),
                ('fog_enabled', models.BooleanField(default=False)),
                ('fog_color', models.CharField(default='#c0c0c0', max_length=7)),
                ('fog_density', models.FloatField(default=0.001)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Освещение мира',
                'verbose_name_plural': 'Освещение миров',
            },
        ),
        migrations.CreateModel(
            name='WorldObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('object_type', models.CharField(choices=[('mesh', 'Меш'), ('light', 'Источник света'), ('spawn', 'Точка спавна'), ('trigger', 'Триггер-зона'), ('empty', 'Пустой (только трансформация)')], default='mesh', max_length=30)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('scale_x', models.FloatField(default=1.0)),
                ('scale_y', models.FloatField(default=1.0)),
                ('scale_z', models.FloatField(default=1.0)),
                ('mesh_asset_id', models.UUIDField(blank=True, null=True)),
                ('material_asset_id', models.UUIDField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объект мира',
                'verbose_name_plural': 'Объекты мира',
            },
        ),
    ]
