# Generated by Django 6.0.5 on 2026-05-10 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Новый мир', max_length=200)),
                ('chunk_size', models.FloatField(default=500.0, help_text='Размер чанка в метрах (диаметр описанной окружности гексагона)')),
                ('max_chunks_horizontal', models.IntegerField(default=100, help_text='Максимальное количество чанков по горизонтали от центра')),
                ('max_chunks_vertical', models.IntegerField(default=20, help_text='Максимальное количество чанков по вертикали (вверх/вниз)')),
                ('default_toolkits', models.JSONField(blank=True, default=list, help_text='Список UUID наборов инструментов, доступных в этом мире')),
                ('lighting', models.JSONField(blank=True, default=dict, help_text='Настройки освещения мира')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='projects.project')),
            ],
            options={
                'verbose_name': 'Мир',
                'verbose_name_plural': 'Миры',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grid_q', models.IntegerField(default=0)),
                ('grid_r', models.IntegerField(default=0)),
                ('grid_s', models.IntegerField(default=0)),
                ('grid_y', models.IntegerField(default=0)),
                ('world_x', models.FloatField(default=0.0)),
                ('world_y', models.FloatField(default=0.0)),
                ('world_z', models.FloatField(default=0.0)),
                ('chunk_type', models.CharField(choices=[('void', 'Пустота — не существует в мире'), ('empty', 'Пустой — ландшафт есть, объектов нет'), ('full', 'Полный — ландшафт + объекты')], default='void', max_length=10)),
                ('is_active', models.BooleanField(default=False, help_text='Чанк готов к редактированию / загружен в память')),
                ('is_loaded', models.BooleanField(default=False, help_text='Чанк загружен клиентом в данный момент')),
                ('top_vertex_x', models.FloatField(default=0.0)),
                ('top_vertex_y', models.FloatField(default=250.0)),
                ('top_vertex_z', models.FloatField(default=0.0)),
                ('bottom_vertex_x', models.FloatField(default=0.0)),
                ('bottom_vertex_y', models.FloatField(default=-250.0)),
                ('bottom_vertex_z', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loaded_by', models.ManyToManyField(blank=True, related_name='loaded_chunks', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='scenes.world')),
            ],
            options={
                'verbose_name': 'Чанк (шестигранная сота)',
                'verbose_name_plural': 'Чанки (шестигранные соты)',
                'indexes': [models.Index(fields=['world', 'grid_q', 'grid_r', 'grid_y'], name='scenes_chun_world_i_4afa73_idx'), models.Index(fields=['is_active'], name='scenes_chun_is_acti_4e81a3_idx')],
                'unique_together': {('world', 'grid_q', 'grid_r', 'grid_y')},
            },
        ),
        migrations.CreateModel(
            name='WorldObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, db_index=True, help_text='Временный ID от клиента (не уникальный)', max_length=150, null=True)),
                ('name', models.CharField(default='Объект', max_length=200)),
                ('object_type', models.CharField(choices=[('mesh', 'Меш (геометрия)'), ('group', 'Группа объектов'), ('light', 'Источник света'), ('spawn', 'Точка спавна'), ('trigger', 'Триггер-зона'), ('empty', 'Пустой (только трансформация)')], default='mesh', max_length=30)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('scale_x', models.FloatField(default=1.0)),
                ('scale_y', models.FloatField(default=1.0)),
                ('scale_z', models.FloatField(default=1.0)),
                ('chunk_q', models.IntegerField(db_index=True, default=0)),
                ('chunk_r', models.IntegerField(db_index=True, default=0)),
                ('chunk_y', models.IntegerField(db_index=True, default=0)),
                ('bounding_radius', models.FloatField(default=1.0, help_text='Радиус описанной сферы для пространственных запросов')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Геометрия, материал, теги, скрипты и прочие свойства')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_objects', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(help_text='Мир, в котором находится объект', on_delete=django.db.models.deletion.CASCADE, related_name='world_objects', to='scenes.world')),
            ],
            options={
                'verbose_name': 'Объект мира',
                'verbose_name_plural': 'Объекты мира',
                'indexes': [models.Index(fields=['world', 'chunk_q', 'chunk_r', 'chunk_y'], name='scenes_worl_world_i_e37e34_idx'), models.Index(fields=['object_type'], name='scenes_worl_object__77eaed_idx'), models.Index(fields=['world', 'position_x', 'position_y', 'position_z'], name='scenes_worl_world_i_4cf116_idx')],
            },
        ),
    ]
