# Generated by Django 6.0.5 on 2026-05-08 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('scenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='loaded_by',
            field=models.ManyToManyField(blank=True, related_name='loaded_chunks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chunkvertex',
            name='chunks',
            field=models.ManyToManyField(related_name='vertices', to='scenes.chunk'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='scenes.scene'),
        ),
        migrations.AddField(
            model_name='world',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='projects.project'),
        ),
        migrations.AddField(
            model_name='scene',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scenes.world'),
        ),
        migrations.AddField(
            model_name='chunkvertex',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertices', to='scenes.world'),
        ),
        migrations.AddField(
            model_name='worldobject',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_objects', to='scenes.chunk'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['scene', 'grid_x', 'grid_y', 'grid_z'], name='scenes_chun_scene_i_a5101e_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['world_x', 'world_y', 'world_z'], name='scenes_chun_world_x_a2cebd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('scene', 'grid_x', 'grid_y', 'grid_z')},
        ),
        migrations.AddIndex(
            model_name='chunkvertex',
            index=models.Index(fields=['world_x', 'world_y', 'world_z'], name='scenes_chun_world_x_1e3d83_idx'),
        ),
    ]
