# Generated by Django 6.0.5 on 2026-05-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='chunk_size',
            field=models.FloatField(default=50.0, help_text='Размер чанка в метрах (диаметр описанной окружности гексагона)'),
        ),
    ]
