# Generated by Django 6.0.5 on 2026-05-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldLighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambient_color', models.CharField(default='#404060', max_length=7)),
                ('ambient_intensity', models.FloatField(default=0.5)),
                ('sun_enabled', models.BooleanField(default=True)),
                ('sun_color', models.CharField(default='#ffffff', max_length=7)),
                ('sun_intensity', models.FloatField(default=1.0)),
                ('sun_rotation_x', models.FloatField(default=45.0)),
                ('sun_rotation_y', models.FloatField(default=30.0)),
                ('fog_enabled', models.BooleanField(default=False)),
                ('fog_color', models.CharField(default='#c0c0c0', max_length=7)),
                ('fog_density', models.FloatField(default=0.001)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('world', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lighting', to='scenes.world')),
            ],
            options={
                'verbose_name': 'Освещение мира',
                'verbose_name_plural': 'Освещение миров',
            },
        ),
    ]
