# Generated by Django 6.0.5 on 2026-05-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Сцена (логическая группа)', 'verbose_name_plural': 'Сцены (логические группы)'},
        ),
        migrations.AddField(
            model_name='scene',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worldobject',
            name='scene',
            field=models.ForeignKey(blank=True, help_text='Логическая группа, к которой относится объект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_objects', to='scenes.scene'),
        ),
    ]
