# Generated by Django 6.0.5 on 2026-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0003_alter_scene_options_scene_is_active_scene_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldobject',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
    ]
