# Generated by Django 6.0.5 on 2026-05-10 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Уникальное системное имя: cube, sphere, pillar', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Отображается на панели: 'Куб', 'Сфера', 'Колонна'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание для подсказки')),
                ('tool_type', models.CharField(choices=[('create_mesh', 'Создать меш'), ('create_light', 'Создать источник света'), ('place_asset', 'Разместить ассет (готовую модель)'), ('transform', 'Трансформация (перемещение/вращение/масштаб)'), ('material', 'Назначить материал'), ('script', 'Привязать скрипт'), ('trigger', 'Создать триггер-зону'), ('spawn', 'Точка спавна'), ('terrain', 'Редактор ландшафта'), ('paint', 'Кисть (раскраска объектов)')], default='create_mesh', max_length=20)),
                ('default_params', models.JSONField(blank=True, default=dict, help_text='Параметры инструмента по умолчанию (геометрия, материал и т.д.)')),
                ('order', models.IntegerField(default=0, help_text='Порядок внутри набора (меньше = выше)')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключен — не показывается нигде')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Инструмент (реестр)',
                'verbose_name_plural': 'Инструменты (реестр)',
                'ordering': ['order', 'tool_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Название набора: 'Базовые фигуры', 'Каменные блоки'", max_length=200)),
                ('icon', models.CharField(default='📦', help_text='Эмодзи или символ для кнопки набора', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Описание набора')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения на панели (меньше = левее/выше)')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключен — набор скрыт у всех')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Кто создал/управляет набором', on_delete=django.db.models.deletion.CASCADE, related_name='toolkits', to=settings.AUTH_USER_MODEL)),
                ('tools', models.ManyToManyField(blank=True, help_text='Инструменты, входящие в набор', related_name='toolkits', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Набор инструментов',
                'verbose_name_plural': 'Наборы инструментов',
                'ordering': ['order', 'name'],
            },
        ),
    ]
