# Generated by Django 6.0.5 on 2026-05-09 05:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Отображается на панели', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tool_type', models.CharField(choices=[('create_mesh', 'Создать меш (куб, сфера, цилиндр)'), ('create_light', 'Создать источник света'), ('transform', 'Инструмент перемещения/вращения/масштаба'), ('material', 'Назначить материал'), ('script', 'Привязать скрипт'), ('trigger', 'Создать триггер-зону'), ('spawn', 'Точка спавна'), ('terrain', 'Редактор ландшафта'), ('paint', 'Кисть (раскраска объектов)')], max_length=20)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG-иконка для панели')),
                ('icon_class', models.CharField(blank=True, help_text='CSS-класс для иконки', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('available_for_all', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
                'ordering': ['order', 'tool_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorldToolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('override', 'Заменить инструменты пользователя'), ('extend', 'Добавить к инструментам пользователя')], default='extend', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инструменты мира',
                'verbose_name_plural': 'Инструменты миров',
            },
        ),
        migrations.CreateModel(
            name='UserToolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tools', models.ManyToManyField(blank=True, related_name='users', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Профиль инструментов пользователя',
                'verbose_name_plural': 'Профили инструментов пользователей',
            },
        ),
    ]
