# Generated by Django 6.0.5 on 2026-05-09 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0002_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoolprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worldtoolprofile',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='worlds', to='tools.tool'),
        ),
        migrations.AddField(
            model_name='worldtoolprofile',
            name='world',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_profile', to='scenes.world'),
        ),
    ]
