# Generated by Django 6.0.5 on 2026-05-11 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Отображаемое имя: 'Колонны', 'Столы', 'Деревья'", max_length=200)),
                ('path', models.CharField(db_index=True, help_text="Полный путь: 'architecture/columns' или 'nature/trees/oak'", max_length=500, unique=True)),
                ('level', models.IntegerField(default=0, help_text='0 = корневая категория, 1 = подкатегория, 2 = под-подкатегория')),
                ('icon', models.CharField(default='📦', help_text='Эмодзи для отображения в тулбаре', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Описание категории')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения (меньше = выше)')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключена — категория скрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская категория (для построения дерева в админке)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tools.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['level', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Все категории, к которым относится инструмент', related_name='tools', to='tools.category'),
        ),
        migrations.AddField(
            model_name='tool',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text='Основная категория для отображения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tools', to='tools.category'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['order', 'tool_type', 'name'], name='tools_tool_order_64e2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_active'], name='tools_tool_is_acti_dc0ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='tools_categ_path_1aa454_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'order'], name='tools_categ_level_678c66_idx'),
        ),
    ]
